### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by CleverSource** [Technach/omni#1]
I hope you don't give up on this project, I hope to see this become something amazing. I'd love to see this be a mix of the discord bot oxyl and chips. Here are the links to the 2 bots discord's you could maybe check them out! 👍 

https://github.com/wzhouwzhou/Chips
https://github.com/minemidnight/oxyl

**Comment by Technach** [comment]
Thank you, so far all I have worked on with this is a core framework but soon I hope to make this an actual fully functional bot. Good luck with your projects as well.
